export default {
  ACTION: 'Action',
  ADVENTURE: 'Adventure',
  ANIMATION: 'Animation',
  COMEDY: 'Comedy',
  CRIME: 'Crime',
  DRAMA: 'Drama',
  DOCUMENTARY: 'Documentary',
  FAMILY: 'Family',
  FANTASY: 'Fantasy',
  HISTORY: 'History',
  HORROR: 'Horror',
  INDEPENDENT: 'Independent',
  MUSICAL: 'Musical',
  MYSTERY: 'Mystery',
  NOIR: 'Noir',
  ROMANCE: 'Romance',
  SPORTS: 'Sports',
  THRILLER: 'Thriller',
  WESTERN: 'Western',
  WAR: 'War'
}

// module.exports = Object.freeze({
//   ACTION: 'Action',
//   ADVENTURE: 'Adventure',
//   ANIMATION: 'Animation',
//   COMEDY: 'Comedy',
//   CRIME: 'Crime',
//   DRAMA: 'Drama',
//   DOCUMENTARY: 'Documentary',
//   FAMILY: 'Family',
//   FANTASY: 'Fantasy',
//   HISTORY: 'History',
//   HORROR: 'Horror',
//   INDEPENDENT: 'Independent',
//   MUSICAL: 'Musical',
//   MYSTERY: 'Mystery',
//   NOIR: 'Noir',
//   ROMANCE: 'Romance',
//   SPORTS: 'Sports',
//   THRILLER: 'Thriller',
//   WESTERN: 'Western',
//   WAR: 'War'
// });
